---
title: "HW2_R_Markdown"
author: "Grace Tan"
date: "September 5, 2020"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

### 2a) Solving a System of Equations  

* 2x + 5y = 33  
* x + 3y = 19

Multiply the second equation by -2

* 2x + 5y = 33  
* -2x - 6y = -38

Eliminate the x-variable through subtraction

-1y = -5  
**y = 5**

### 2b) Vector Creation

```{r vector}
vector_100 <- c(1:100)
is.vector("vector_100")
table(vector_100)
```

Calculate the mean of the 0-100 sequence without using the mean function
```{r mean}
sum(vector_100)/length(vector_100)
```

Check with the mean function!
```{r mean formula}
mean(vector_100)
```

### 2c) Install the dplyr package and create a data frame

```{r data}
library(dbplyr)
first_column <- c("A","D")
second_column <- c("B","E")
third_column <- c("C","F")
fourth_column <- c("D","G")
letters <- data.frame(first_column, second_column, third_column, fourth_column)
print(letters)
is.data.frame(letters)
```